Updated pipeline

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -60,10 +60,24 @@ jobs:
         USERNAME: ${{ secrets.anypoint_platform_username }}
         PASSWORD: ${{ secrets.anypoint_platform_password }}
       run: |
-        artifactName=$(ls *.jar | head -1)
-        timeout 1800s mvn deploy -DmuleDeploy \
-         -Dmule.artifact=$artifactName \
-         -Danypoint.username="$USERNAME" \
-         -Danypoint.password="$PASSWORD"
-         -Dhttp.socketTimeout=60000 \
-         -Dhttp.connectionTimeout=60000 && break || sleep 20;
+        retry_count=0
+        max_retries=5
+        delay=30
+        until [ $retry_count -ge $max_retries ]
+        do
+          artifactName=$(ls *.jar | head -1)
+          timeout 1800s mvn deploy -DmuleDeploy \
+            -Dmule.artifact=$artifactName \
+            -Danypoint.username="$USERNAME" \
+            -Danypoint.password="$PASSWORD"
+            -Dhttp.socketTimeout=60000 \
+            -Dhttp.connectionTimeout=60000 && break || sleep 20;
+          retry_count=$[$retry_count+1]
+          echo "Deployment failed. Retrying in $delay seconds..."
+          sleep $delay
+          delay=$[$delay*2]
+        done
+      if [ $retry_count -ge $max_retries ]; then
+          echo "Deployment failed after $max_retries attempts."
+         exit 1
+      fi
